apiVersion: apps/v1
kind: Deployment
metadata:
  name: cargo-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cargo-svc
  template:
    metadata:
      labels:
        app: cargo-svc
    spec:
      containers:
        - name: cargo-svc
          image: cargo_svc:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
---
apiVersion: v1
kind: Service
metadata:
  name: cargo-svc
spec:
  selector:
    app: cargo-svc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
